In [79]:
import numpy as np
import pandas as pd
from cond import CalculateProb
from draw import randomDraw
import random as rd
#PS, EA, MR
#read in csv of conditional matrix here. Conditional Matrix contains likelihood that ohter nodes will be infected given
#an initial condition that represents which nodes are already compromised. Initial condition(s) are in the csv.
conditional  =  pd.read_csv("net1.csv")

#seperate out M, the probability matrix, and N the Node matrix
numCol = len(conditional.columns)
M = np.array(conditional.iloc[0:numCol])
N = np.array(conditional.iloc[numCol:numCol+1])
print(N)
N = N[0]

[[1. 1. 0. 0. 0. 0.]]


In [89]:
#Create a list of nodes that the User wants to watch for compromise. 
#This list will determine how long the simulation will run. 
Watch = N.tolist()
print (Watch)

[1.0, 1.0, 0.0, 0.0, 0.0, 0.0]


In [94]:
# Checks to see if the nodes in watch are compromised or not. Returns a boolean.
def isCompromised(Watch):
    if(Watch.count(1)>1):
        return True
    return False

isCompromised(Watch)

True

In [95]:
randomDraw(Watch)


array([1., 1., 0., 0., 0., 0.])

In [106]:
#Calculate Probabilities and update N for next step
p = CalculateProb(M,N)
print(p)
for i in range(len(p)):
    if(N[i] == 0):
        N[i] = p[i]
print(N)

[0.2        0.         0.88       0.704      0.44       0.65353899]
[1.    1.    0.88  0.704 0.44  0.088]
