In [94]:
import numpy as np
import pandas as pd
from cond import CalculateProb
from draw import randomDraw
import random as rd

#PS, EA, MR
#read in csv of conditional matrix here. Conditional Matrix contains likelihood that ohter nodes will be infected given
#an initial condition that represents which nodes are already compromised. Initial condition(s) are in the csv.
conditional  =  pd.read_csv("net1.csv")

#seperate out M, the probability matrix, and N the Node matrix
numCol = len(conditional.columns)
M = np.array(conditional.iloc[0:numCol])
N = np.array(conditional.iloc[numCol:numCol+1])
print(M)
print(N)
N = N[0]



[[0.   0.   0.7  0.   0.   0.  ]
 [0.2  0.   0.6  0.   0.   0.  ]
 [0.   0.   0.   0.8  0.5  0.1 ]
 [0.   0.   0.   0.   0.   0.66]
 [0.   0.   0.   0.   0.   0.66]
 [0.   0.   0.   0.   0.   0.  ]]
[[1. 1. 0. 0. 0. 0.]]


In [90]:
#Create a list of nodes that the User wants to watch for compromise. 
#This list will determine how long the simulation will run. 
Watch = [1, 1, 0, 1, 1, 1]
# Checks to see if the nodes in watch are compromised or not. Returns a boolean.

def isCompromised():
    compromisedNodes = Watch.count(1)
    count = 0
    for i in range(len(Watch)):
        if(Watch[i] == N[i]):
            count= count+1
    if(compromisedNodes == count):
        return True
    return False

In [91]:
#Calculate Probabilities and update N for next step
p = CalculateProb(M,N)
print(p)

for i in range(len(p)):
    if(N[i] != 1):
        N[i] = p[i]
N = randomDraw(N)
print("Next Comprosied State: ", N)

[0.2  0.   0.88 0.   0.   0.  ]
Next Comprosied State:  [1. 1. 1. 0. 0. 0.]


In [95]:
n = 5 # Number of iterations
num_steps = []
for i in range(n):
    p = CalculateProb(M,N)
    for j in range(len(p)):
        if(N[j] != 1):
            N[j] = p[i]
    N = randomDraw(N)
    if(isCompromised()):
        num_steps.append(n)
        break
print("Number of Steps Taken: ", num_steps)
print("N vector: ", N)

Number of Steps Taken:  [5]
N vector:  [1. 1. 1. 1. 1. 1.]
