In [172]:
import numpy as np
import pandas as pd
from cond import CalculateProb
from draw import randomDraw
import random as rd

#PS, EA, MR
#read in csv of conditional matrix here. Conditional Matrix contains likelihood that ohter nodes will be infected given
#an initial condition that represents which nodes are already compromised. Initial condition(s) are in the csv.
conditional  =  pd.read_csv("net1.csv")

#seperate out M, the probability matrix, and N the Node matrix
numCol = len(conditional.columns)
M = np.array(conditional.iloc[0:numCol])
N = np.array(conditional.iloc[numCol:numCol+1])
print(M)
print(N)
initN = N[0]
N = N[0]

[[0.   0.   0.7  0.   0.   0.  ]
 [0.2  0.   0.6  0.   0.   0.  ]
 [0.   0.   0.   0.8  0.5  0.1 ]
 [0.   0.   0.   0.   0.   0.66]
 [0.   0.   0.   0.   0.   0.66]
 [0.   0.   0.   0.   0.   0.  ]]
[[1. 1. 0. 0. 0. 0.]]


In [202]:
#Create a list of nodes that the User wants to watch for compromise. 
#This list will determine how long the simulation will run. 
Watch = [1, 1, 0, 1, 1, 1]
# Checks to see if the nodes in watch are compromised or not. Returns a boolean.

def isCompromised():
    count = 0
    watch_ones = np.where(np.array(Watch) == 1)
    N_ones = np.where(np.array(N) == 1)
    return set(watch_ones[0]).issubset(set(N_ones[0]))

In [211]:
n = 10 # Number of iterations
num_steps = []
for i in range(n):
    print("Interation: ", i)
    N = initN
    count = 0
    while(not isCompromised()):
        p = CalculateProb(M,N)
        for j in range(len(p)):
            if(N[j] != 1):
                N[j] = p[j]
        print("Next Step Prob:", p)
        N = randomDraw(N)
        count = count + 1
    num_steps.append(count)
    print("Number of Steps Taken: ", num_steps[len(num_steps)-1])
    print("N vector: ", N)
    print("")


Interation:  0
Next Step Prob: [0.2        0.         0.88       0.704      0.44       0.65353899]
Next Step Prob: [0.2   0.    0.88  0.8   0.5   0.694]
Number of Steps Taken:  2
N vector:  [1. 1. 1. 1. 1. 1.]

Interation:  1
Next Step Prob: [0.2        0.         0.88       0.704      0.44       0.65353899]
Next Step Prob: [0.2   0.    0.88  0.8   0.5   0.694]
Next Step Prob: [0.2   0.    0.88  0.8   0.5   0.694]
Number of Steps Taken:  3
N vector:  [1. 1. 1. 1. 1. 1.]

Interation:  2
Next Step Prob: [0.2        0.         0.88       0.704      0.44       0.65353899]
Next Step Prob: [0.2   0.    0.88  0.8   0.5   0.694]
Number of Steps Taken:  2
N vector:  [1. 1. 1. 1. 1. 1.]

Interation:  3
Next Step Prob: [0.2        0.         0.88       0.704      0.44       0.65353899]
Next Step Prob: [0.2  0.   0.88 0.   0.   0.66]
Next Step Prob: [0.2   0.    0.88  0.8   0.5   0.694]
Next Step Prob: [0.2   0.    0.88  0.8   0.5   0.694]
Number of Steps Taken:  4
N vector:  [1. 1. 1. 1. 1. 1.]

