In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from cond import CalculateProb
from draw import randomDraw
import random as rd
from generator import gen_network
from generator import gen_states
from generator import watch
import Plotting 


#PS, EA, MR
#read in csv of conditional matrix here. Conditional Matrix contains likelihood that ohter nodes will be infected given
#an initial condition that represents which nodes are already compromised. Initial condition(s) are in the csv.
conditional  =  pd.read_csv("net1.csv")
size = 10
#seperate out M, the probability matrix, and N the Node matrix
numCol = len(conditional.columns)
M = gen_network(size)
N = gen_states(size)
print(M)
print(N)
initN = N


#Create a list of nodes that the User wants to watch for compromise. 
#This list will determine how long the simulation will run. 
Watch = watch(size)
print("Watch Vector:", Watch)
# Checks to see if the nodes in watch are compromised or not. Returns a boolean.
def isCompromised():
    count = 0
    watch_ones = np.where(np.array(Watch) == 1)
    N_ones = np.where(np.array(N) == 1)
    return set(watch_ones[0]).issubset(set(N_ones[0]))


n = 10 # Number of iterations
num_steps = []
for i in range(n):
    #print("Interation: ", i)
    N = initN
    count = 0
    while(not isCompromised()):
        p = CalculateProb(M,N)
        for j in range(len(p)):
            if(N[j] != 1):
                N[j] = p[j]
        #print("Next Step Prob:", p)
        N = randomDraw(N)
        count = count + 1
    num_steps.append(count)
    #print("Number of Steps Taken: ", num_steps[len(num_steps)-1])
    #print("N vector: ", N)
    #print("")
print("Number of Steps Taken: ", num_steps)

Plotting.plotMatrix(M)
Plotting.barChart(num_steps)

ModuleNotFoundError: No module named 'networkx'

In [43]:
cvcData = pd.read_csv("MS10PrivData.csv")
scoreVector = 1- cvcData['Score']*0.10
#print(scoreVector)
n =10
#network = np.full((n,n), scoreVector)
network = scoreVector
network = np.array(network)
#print(scoreVector)
network = np.random.choice(scoreVector, n*n)
network = np.reshape(network, (n,n), 'F')
print(network)
np.fill_diagonal(network, 1)
network = np.triu(network, 0) 
for i in range(n):
    np.fill_diagonal(network[:,(i+5 %n):], 0)
print(len(network))
#print(100-(cvcData.score*10))

[[0.28 0.28 0.28 0.28 0.56 0.28 0.28 0.28 0.57 0.28]
 [0.28 0.28 0.28 0.07 0.28 0.28 0.64 0.28 0.28 0.28]
 [0.31 0.28 0.31 0.28 0.28 0.28 0.28 0.56 0.07 0.28]
 [0.28 0.28 0.28 0.28 0.28 0.28 0.07 0.28 0.07 0.31]
 [0.07 0.28 0.28 0.28 0.57 0.28 0.07 0.28 0.28 0.07]
 [0.31 0.28 0.28 0.07 0.28 0.28 0.28 0.56 0.07 0.31]
 [0.31 0.56 0.28 0.28 0.31 0.28 0.28 0.28 0.28 0.07]
 [0.54 0.28 0.28 0.28 0.28 0.28 0.   0.31 0.31 0.28]
 [0.07 0.56 0.31 0.28 0.   0.28 0.28 0.28 0.28 0.28]
 [0.28 0.28 0.28 0.   0.64 0.28 0.28 0.56 0.07 0.28]]
10
